In this notebook, we're going to be fitting our first model for Emotion/Stress detection, which is an SVM Classifier Model.

In [9]:
import numpy as np 
import pandas as pd
from sklearn import svm 
from sklearn.preprocessing import StandardScaler

Now, we load our processed data and store it in the following containers, ready to fit in the data. 

In [10]:
train_df = pd.read_csv("/Users/almarai/Private Projects/CogniScan/CogniScan/data/processed/train_data_processed.csv")
test_df = pd.read_csv("/Users/almarai/Private Projects/CogniScan/CogniScan/data/processed/test_data_processed.csv")

In [11]:
train_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2295,2296,2297,2298,2299,2300,2301,2302,2303,emotion
0,70,80,82,72,58,58,60,63,54,58,...,182,183,136,106,116,95,106,109,82,0
1,151,150,147,155,148,133,111,140,170,174,...,108,95,108,102,67,171,193,183,184,0
2,231,212,156,164,174,138,161,173,182,200,...,138,152,122,114,101,97,88,110,152,0
3,24,32,36,30,32,23,19,20,30,41,...,126,132,132,133,136,139,142,143,142,0
4,4,0,0,0,0,0,0,0,0,0,...,34,31,31,31,27,31,30,29,30,2


In [12]:
X_train = train_df.drop(columns = ["emotion"])
y_train = train_df["emotion"]

X_test = test_df.drop(columns = ["emotion"])
y_test = test_df["emotion"]

# #Before fitting out model, we need to scale our features and target
# scaler = StandardScaler()
# scaler.fit(X_train)

# X_train_scaled = scaler.transform(X_train)
# X_test_scaled = scaler.transform(X_test)

In [13]:
X_train_small = train_df.iloc[:1000,:].drop(columns = ["emotion"])
y_train_small = train_df.iloc[:1000,:]["emotion"]
X_train_small.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 2304 entries, 0 to 2303
dtypes: int64(2304)
memory usage: 17.6 MB


In [14]:
scaler = StandardScaler()

scaler.fit(X_train_small)

X_train_scaled = scaler.transform(X_train_small)

Now we create a basic model, to check it's performance before we perform some hyperparameter tuning. 

In [15]:
model = svm.SVC(
    kernel='linear',
    C=1.0,
    gamma='scale',
    probability=True
)
model.fit(X_train_scaled, y_train_small)

y_pred = model.predict(X_train_scaled)

In [17]:
from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(y_pred, y_train_small))
print(classification_report(y_pred,y_train_small))

[[474   0   0]
 [  0 354   0]
 [  0   0 172]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       474
           1       1.00      1.00      1.00       354
           2       1.00      1.00      1.00       172

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000



So we've identified that the issue with the training of the model, is that the number of observations are too many and the computational time for training is becoming increasingly large. 